import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import {Providers} from "@/components/providers";
import { Toaster } from "sonner";

const jetbrainsMono = JetBrains_Mono({
  variable: "--fonts-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.className} antialiased`}>
        <Toaster richColors closeButton position="top-center"/>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
